# Generated by Django 2.0.2 on 2018-02-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180214_1119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choix',
            new_name='Choice',
        ),
    ]
