# Generated by Django 2.0.2 on 2018-02-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_sondage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sondage',
            name='question_sondage',
        ),
        migrations.AddField(
            model_name='sondage',
            name='question_sondage',
            field=models.ManyToManyField(blank=True, default=None, to='polls.Question'),
        ),
    ]
