# Generated by Django 2.0.2 on 2018-02-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180215_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondage',
            name='question_sondage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
