# Generated by Django 2.0.2 on 2018-02-15 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180215_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sondage',
            name='question_sondage',
        ),
        migrations.DeleteModel(
            name='Sondage',
        ),
    ]
